import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import { Provider } from 'react-redux';
import store from '../store/index';
import Head from 'next/head';
import 'react-perfect-scrollbar/dist/css/styles.css';
import '../styles/tailwind.css';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ToastContainer } from 'react-toastify';
import DefaultLayout from '../components/Layouts/DefaultLayout';

const queryClient = new QueryClient();

const App = ({ Component, pageProps }: AppProps) => {
    const router = useRouter();
    const noLayoutPages = ['/login'];

    const isNoLayoutPage = noLayoutPages.includes(router.pathname);

    return (
        <QueryClientProvider client={queryClient}>
            <Provider store={store}>
                <Head>
                    <title>myTest</title>
                    <meta charSet="UTF-8" />
                    <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <ToastContainer />
                {isNoLayoutPage ? (
                    <Component {...pageProps} />
                ) : (
                    <DefaultLayout>
                        <Component {...pageProps} />
                    </DefaultLayout>
                )}
            </Provider>
        </QueryClientProvider>
    );
};

export default App;
